/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Bootcamp Treinos API
 * API para o bootcamp de treinos do FSC
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "../../fetch";
export type Get200 = {
  message: string;
};

export type UpdateWorkoutSession500 = {
  code: string;
  error: string;
};

export type UpdateWorkoutSession404 = {
  code: string;
  error: string;
};

export type UpdateWorkoutSession401 = {
  code: string;
  error: string;
};

export type UpdateWorkoutSession200 = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startedAt: string;
};

export type UpdateWorkoutSessionBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
};

export type StartWorkoutSession500 = {
  code: string;
  error: string;
};

export type StartWorkoutSession422 = {
  code: string;
  error: string;
};

export type StartWorkoutSession409 = {
  code: string;
  error: string;
};

export type StartWorkoutSession404 = {
  code: string;
  error: string;
};

export type StartWorkoutSession401 = {
  code: string;
  error: string;
};

export type StartWorkoutSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userWorkoutSessionId: string;
};

export type GetWorkoutDay500 = {
  code: string;
  error: string;
};

export type GetWorkoutDay404 = {
  code: string;
  error: string;
};

export type GetWorkoutDay401 = {
  code: string;
  error: string;
};

export type GetWorkoutDay200WeekDay =
  (typeof GetWorkoutDay200WeekDay)[keyof typeof GetWorkoutDay200WeekDay];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetWorkoutDay200WeekDay = {
  Monday: "Monday",
  Tuesday: "Tuesday",
  Wednesday: "Wednesday",
  Thursday: "Thursday",
  Friday: "Friday",
  Saturday: "Saturday",
  Sunday: "Sunday",
} as const;

export type GetWorkoutDay200SessionsItem = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$ */
  completedAt?: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$ */
  startedAt?: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
};

export type GetWorkoutDay200ExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  reps: number;
  restTimeInSeconds: number;
  sets: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
};

export type GetWorkoutDay200 = {
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  exercises: GetWorkoutDay200ExercisesItem[];
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  isRest: boolean;
  name: string;
  sessions: GetWorkoutDay200SessionsItem[];
  weekDay: GetWorkoutDay200WeekDay;
};

export type GetWorkoutPlan500 = {
  code: string;
  error: string;
};

export type GetWorkoutPlan404 = {
  code: string;
  error: string;
};

export type GetWorkoutPlan401 = {
  code: string;
  error: string;
};

export type GetWorkoutPlan200WorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlan200WorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlan200WorkoutDaysItemWeekDay];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetWorkoutPlan200WorkoutDaysItemWeekDay = {
  Monday: "Monday",
  Tuesday: "Tuesday",
  Wednesday: "Wednesday",
  Thursday: "Thursday",
  Friday: "Friday",
  Saturday: "Saturday",
  Sunday: "Sunday",
} as const;

export type GetWorkoutPlan200WorkoutDaysItem = {
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  isRest: boolean;
  name: string;
  weekDay: GetWorkoutPlan200WorkoutDaysItemWeekDay;
};

export type GetWorkoutPlan200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  workoutDays: GetWorkoutPlan200WorkoutDaysItem[];
};

export type CreateWorkoutPlan500 = {
  code: string;
  error: string;
};

export type CreateWorkoutPlan404 = {
  code: string;
  error: string;
};

export type CreateWorkoutPlan401 = {
  code: string;
  error: string;
};

export type CreateWorkoutPlan400 = {
  code: string;
  error: string;
};

export type CreateWorkoutPlan201WorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateWorkoutPlan201WorkoutDaysItemWeekDay = {
  Monday: "Monday",
  Tuesday: "Tuesday",
  Wednesday: "Wednesday",
  Thursday: "Thursday",
  Friday: "Friday",
  Saturday: "Saturday",
  Sunday: "Sunday",
} as const;

export type CreateWorkoutPlan201WorkoutDaysItem = {
  coverImageUrl?: string;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[];
  isRest: boolean;
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlan201WorkoutDaysItemWeekDay;
};

export type CreateWorkoutPlan201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlan201WorkoutDaysItem[];
};

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
  /** @minLength 1 */
  name: string;
  /** @minimum 0 */
  order: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
  /** @minimum 1 */
  sets: number;
};

export type CreateWorkoutPlanBody = {
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[];
};

export type CreateWorkoutPlanBodyWorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  Monday: "Monday",
  Tuesday: "Tuesday",
  Wednesday: "Wednesday",
  Thursday: "Thursday",
  Friday: "Friday",
  Saturday: "Saturday",
  Sunday: "Sunday",
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /** @minLength 1 */
  name: string;
  /** @minimum 0 */
  order: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
  /** @minimum 1 */
  sets: number;
};

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  coverImageUrl?: string;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[];
  isRest?: boolean;
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlanBodyWorkoutDaysItemWeekDay;
};

export type ListWorkoutPlans500 = {
  code: string;
  error: string;
};

export type ListWorkoutPlans401 = {
  code: string;
  error: string;
};

export type ListWorkoutPlans200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  isActive: boolean;
  name: string;
  workoutDays: ListWorkoutPlans200ItemWorkoutDaysItem[];
};

export type ListWorkoutPlans200ItemWorkoutDaysItemWeekDay =
  (typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay)[keyof typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListWorkoutPlans200ItemWorkoutDaysItemWeekDay = {
  Monday: "Monday",
  Tuesday: "Tuesday",
  Wednesday: "Wednesday",
  Thursday: "Thursday",
  Friday: "Friday",
  Saturday: "Saturday",
  Sunday: "Sunday",
} as const;

export type ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  reps: number;
  restTimeInSeconds: number;
  sets: number;
};

export type ListWorkoutPlans200ItemWorkoutDaysItem = {
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  exercises: ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem[];
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  isRest: boolean;
  name: string;
  weekDay: ListWorkoutPlans200ItemWorkoutDaysItemWeekDay;
};

export type ListWorkoutPlansActive =
  (typeof ListWorkoutPlansActive)[keyof typeof ListWorkoutPlansActive];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListWorkoutPlansActive = {
  true: "true",
  false: "false",
} as const;

export type ListWorkoutPlansParams = {
  active?: ListWorkoutPlansActive;
};

export type GetStats500 = {
  code: string;
  error: string;
};

export type GetStats404 = {
  code: string;
  error: string;
};

export type GetStats401 = {
  code: string;
  error: string;
};

export type GetStats200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetStats200 = {
  completedWorkoutsCount: number;
  conclusionRate: number;
  consistencyByDay: GetStats200ConsistencyByDay;
  totalTimeInSeconds: number;
  workoutStreak: number;
};

export type GetStatsParams = {
  from: string;
  to: string;
};

export type UpsertUserTrainData500 = {
  code: string;
  error: string;
};

export type UpsertUserTrainData401 = {
  code: string;
  error: string;
};

export type UpsertUserTrainData200 = {
  age: number;
  bodyFatPercentage: number;
  heightInCentimeters: number;
  userId: string;
  weightInGrams: number;
};

export type UpsertUserTrainDataBody = {
  /** @minimum 0 */
  age: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  bodyFatPercentage: number;
  /** @minimum 0 */
  heightInCentimeters: number;
  /** @minimum 0 */
  weightInGrams: number;
};

export type GetUserTrainData500 = {
  code: string;
  error: string;
};

export type GetUserTrainData401 = {
  code: string;
  error: string;
};

/**
 * @nullable
 */
export type GetUserTrainData200 = {
  age: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  bodyFatPercentage: number;
  heightInCentimeters: number;
  userId: string;
  userName: string;
  weightInGrams: number;
} | null;

export type GetHomeData500 = {
  code: string;
  error: string;
};

export type GetHomeData404 = {
  code: string;
  error: string;
};

export type GetHomeData401 = {
  code: string;
  error: string;
};

export type GetHomeData200TodayWorkoutDayWeekDay =
  (typeof GetHomeData200TodayWorkoutDayWeekDay)[keyof typeof GetHomeData200TodayWorkoutDayWeekDay];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetHomeData200TodayWorkoutDayWeekDay = {
  Monday: "Monday",
  Tuesday: "Tuesday",
  Wednesday: "Wednesday",
  Thursday: "Thursday",
  Friday: "Friday",
  Saturday: "Saturday",
  Sunday: "Sunday",
} as const;

export type GetHomeData200TodayWorkoutDay = {
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  isRestDay: boolean;
  name: string;
  weekDay: GetHomeData200TodayWorkoutDayWeekDay;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
};

export type GetHomeData200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetHomeData200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  activeWorkoutPlanId: string;
  consistencyByDay: GetHomeData200ConsistencyByDay;
  todayWorkoutDay?: GetHomeData200TodayWorkoutDay;
  workoutStreak: number;
};

/**
 * @summary Get home page data
 */
export type getHomeDataResponse = {
  data: GetHomeData200;
  status: number;
};

export const getGetHomeDataUrl = (date: string) => {
  return `/home/${date}`;
};

export const getHomeData = async (
  date: string,
  options?: RequestInit,
): Promise<getHomeDataResponse> => {
  return customFetch<Promise<getHomeDataResponse>>(getGetHomeDataUrl(date), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get user train data
 */
export type getUserTrainDataResponse = {
  data: GetUserTrainData200;
  status: number;
};

export const getGetUserTrainDataUrl = () => {
  return `/me/`;
};

export const getUserTrainData = async (
  options?: RequestInit,
): Promise<getUserTrainDataResponse> => {
  return customFetch<Promise<getUserTrainDataResponse>>(
    getGetUserTrainDataUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Upsert user train data
 */
export type upsertUserTrainDataResponse = {
  data: UpsertUserTrainData200;
  status: number;
};

export const getUpsertUserTrainDataUrl = () => {
  return `/me/`;
};

export const upsertUserTrainData = async (
  upsertUserTrainDataBody: UpsertUserTrainDataBody,
  options?: RequestInit,
): Promise<upsertUserTrainDataResponse> => {
  return customFetch<Promise<upsertUserTrainDataResponse>>(
    getUpsertUserTrainDataUrl(),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(upsertUserTrainDataBody),
    },
  );
};

/**
 * @summary Get user workout stats
 */
export type getStatsResponse = {
  data: GetStats200;
  status: number;
};

export const getGetStatsUrl = (params: GetStatsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value === null) {
      normalizedParams.append(key, "null");
    } else if (value !== undefined) {
      normalizedParams.append(key, value.toString());
    }
  });

  return normalizedParams.size
    ? `/stats/?${normalizedParams.toString()}`
    : `/stats/`;
};

export const getStats = async (
  params: GetStatsParams,
  options?: RequestInit,
): Promise<getStatsResponse> => {
  return customFetch<Promise<getStatsResponse>>(getGetStatsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary List workout plans
 */
export type listWorkoutPlansResponse = {
  data: ListWorkoutPlans200Item[];
  status: number;
};

export const getListWorkoutPlansUrl = (params?: ListWorkoutPlansParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value === null) {
      normalizedParams.append(key, "null");
    } else if (value !== undefined) {
      normalizedParams.append(key, value.toString());
    }
  });

  return normalizedParams.size
    ? `/workout-plans/?${normalizedParams.toString()}`
    : `/workout-plans/`;
};

export const listWorkoutPlans = async (
  params?: ListWorkoutPlansParams,
  options?: RequestInit,
): Promise<listWorkoutPlansResponse> => {
  return customFetch<Promise<listWorkoutPlansResponse>>(
    getListWorkoutPlansUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Create a workout plan
 */
export type createWorkoutPlanResponse = {
  data: CreateWorkoutPlan201;
  status: number;
};

export const getCreateWorkoutPlanUrl = () => {
  return `/workout-plans/`;
};

export const createWorkoutPlan = async (
  createWorkoutPlanBody: CreateWorkoutPlanBody,
  options?: RequestInit,
): Promise<createWorkoutPlanResponse> => {
  return customFetch<Promise<createWorkoutPlanResponse>>(
    getCreateWorkoutPlanUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(createWorkoutPlanBody),
    },
  );
};

/**
 * @summary Get a workout plan
 */
export type getWorkoutPlanResponse = {
  data: GetWorkoutPlan200;
  status: number;
};

export const getGetWorkoutPlanUrl = (workoutPlanId: string) => {
  return `/workout-plans/${workoutPlanId}`;
};

export const getWorkoutPlan = async (
  workoutPlanId: string,
  options?: RequestInit,
): Promise<getWorkoutPlanResponse> => {
  return customFetch<Promise<getWorkoutPlanResponse>>(
    getGetWorkoutPlanUrl(workoutPlanId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get a workout day
 */
export type getWorkoutDayResponse = {
  data: GetWorkoutDay200;
  status: number;
};

export const getGetWorkoutDayUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}`;
};

export const getWorkoutDay = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<getWorkoutDayResponse> => {
  return customFetch<Promise<getWorkoutDayResponse>>(
    getGetWorkoutDayUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Start a workout session
 */
export type startWorkoutSessionResponse = {
  data: StartWorkoutSession201;
  status: number;
};

export const getStartWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`;
};

export const startWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<startWorkoutSessionResponse> => {
  return customFetch<Promise<startWorkoutSessionResponse>>(
    getStartWorkoutSessionUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Update a workout session
 */
export type updateWorkoutSessionResponse = {
  data: UpdateWorkoutSession200;
  status: number;
};

export const getUpdateWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}`;
};

export const updateWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
  updateWorkoutSessionBody: UpdateWorkoutSessionBody,
  options?: RequestInit,
): Promise<updateWorkoutSessionResponse> => {
  return customFetch<Promise<updateWorkoutSessionResponse>>(
    getUpdateWorkoutSessionUrl(workoutPlanId, workoutDayId, sessionId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(updateWorkoutSessionBody),
    },
  );
};

/**
 * @summary Chat with AI personal trainer
 */
export type postAiResponse = {
  data: void;
  status: number;
};

export const getPostAiUrl = () => {
  return `/ai/`;
};

export const postAi = async (
  options?: RequestInit,
): Promise<postAiResponse> => {
  return customFetch<Promise<postAiResponse>>(getPostAiUrl(), {
    ...options,
    method: "POST",
  });
};

/**
 * Hello world
 */
export type getResponse = {
  data: Get200;
  status: number;
};

export const getGetUrl = () => {
  return `/`;
};

export const get = async (options?: RequestInit): Promise<getResponse> => {
  return customFetch<Promise<getResponse>>(getGetUrl(), {
    ...options,
    method: "GET",
  });
};
